language: python

python:
#  - '2.7'
  - '3.8'
#  - 'pypy'
#  - 'pypy3'

matrix:
  include:
    - name: "osx: Python 2.7"
      os: osx
      language: generic
      before_install:
        - python --version
        - export PATH=$(python -c 'import site; print(site.USER_BASE)')/bin:$PATH
        - export PATH=/usr/local/Cellar/numpy/1.14.5/libexec/nose/bin:$PATH
        - pip install --upgrade pip
      install:
        - pip install coveralls --user

    - os: osx
      addons:
        homebrew:
          update: true
          packages:
            - pyenv
      language: generic
      python: '3.8.0'
      before_install:
        - export PYENV_VERSION='3.8.0' # eval "$(pyenv init -)"
        - echo $PYENV_VERSION
        - pyenv install $PYENV_VERSION
        - export PATH="${HOME}/.pyenv/shims:${PATH}"
        - echo $PATH
        - python --version
#        - which pip
#        - pip --version
#        - python3 --version
#        - export PATH=/usr/local/Cellar/numpy/1.14.5/libexec/nose/bin:$PATH
#        - sudo pip3 install --upgrade pip
#      install:
#        - sudo pip3 install coveralls
#      script:
#        - nosetests-3.6 --with-coverage --cover-package=terminalplot
#      after_success: coveralls

install:
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=terminalplot

after_success:
  coveralls

deploy:
  provider: pypi
  user: kressi
  password:
    secure: Rw31x5q4kz2Byld5JuboAxEISR4OIrJdobKU1mmJI8CQL8IuZOuv0w8Y7DxljQLzvCigtPFfqXkdARCXiKeYwKUAQaTVRVRf5DpPQsYlnSS8/0b6vr7XEiICkIjQN0CtB/oyXjLA7nZebgeRj45iVf4nDSzyQnjiIXpfIUTqLnA=
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = '3.5'

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: "__token__"
  #password: "pypi-AgENdGVzdC5weXBpLm9yZwIkYjcxZDIwMTgtYzczOC00NjQyLWEzZjAtYmM4NGZlNGZlODZmAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiCG2NKKCcYBW5OY02J-jjqHpJsgxU2dWV9WWqj9F5ZbIw"
  distributions: sdist bdist_wheel
  on:
    branch: develop
    condition: $TRAVIS_OS_NAME == 'linux' && $TRAVIS_PYTHON_VERSION = '3.8'
