language: python

python:
#  - '2.7'
  - '3.8'
#  - 'pypy'
#  - 'pypy3'

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          update: true
          packages:
            - python # avoid 'ERROR:root:code for hash md5 was not found.' of pyenv
            - pyenv
      language: bash
      python: '3.8.0'
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/.pyenv/versions
      before_cache:
        - brew cleanup
      before_install:
        - export PYENV_VERSION='3.8.0' # eval "$(pyenv init -)"
        - pyenv install $PYENV_VERSION
        - export PATH="${HOME}/.pyenv/shims:${PATH}"
        - pip install --upgrade pip
        - pip install nose
    - os: windows
      language: bash
      python: '3.8.0'
      before_install:
        - echo $PATH
        - export PYTHON_VERSION='3.8.0'
        - choco list python --all
        - choco help
        - choco install python --version $PYTHON_VERSION
        - python -m pip install --upgrade pip
        - pip install nose
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=terminalplot

after_success:
  coveralls

deploy:
  provider: pypi
  user: kressi
  password:
    secure: Rw31x5q4kz2Byld5JuboAxEISR4OIrJdobKU1mmJI8CQL8IuZOuv0w8Y7DxljQLzvCigtPFfqXkdARCXiKeYwKUAQaTVRVRf5DpPQsYlnSS8/0b6vr7XEiICkIjQN0CtB/oyXjLA7nZebgeRj45iVf4nDSzyQnjiIXpfIUTqLnA=
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = '3.5'

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: "__token__"
  #password: "pypi-AgENdGVzdC5weXBpLm9yZwIkYjcxZDIwMTgtYzczOC00NjQyLWEzZjAtYmM4NGZlNGZlODZmAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiCG2NKKCcYBW5OY02J-jjqHpJsgxU2dWV9WWqj9F5ZbIw"
  distributions: sdist bdist_wheel
  on:
    branch: develop
    condition: $TRAVIS_OS_NAME == 'linux' && $TRAVIS_PYTHON_VERSION = '3.8'
