language: python
python:
- '2.7'
- '3.5'
- 'pypy'
- 'pypy3'
install:
- pip install coveralls
script:
- nosetests --with-coverage --cover-package=terminalplot
after_success:
  coveralls
deploy:
  provider: pypi
  user: kressi
  password:
    secure: Rw31x5q4kz2Byld5JuboAxEISR4OIrJdobKU1mmJI8CQL8IuZOuv0w8Y7DxljQLzvCigtPFfqXkdARCXiKeYwKUAQaTVRVRf5DpPQsYlnSS8/0b6vr7XEiICkIjQN0CtB/oyXjLA7nZebgeRj45iVf4nDSzyQnjiIXpfIUTqLnA=
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = '3.5'
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: "__token__"
  password: "pypi-AgENdGVzdC5weXBpLm9yZwIkYjcxZDIwMTgtYzczOC00NjQyLWEzZjAtYmM4NGZlNGZlODZmAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiCG2NKKCcYBW5OY02J-jjqHpJsgxU2dWV9WWqj9F5ZbIw"
  distributions: sdist bdist_wheel
  on:
    branch: develop
    skip_existing: true
    condition: $TRAVIS_PYTHON_VERSION = '3.5'
