language: python

python:
  - '2.7'
  - '3.8'
  - 'pypy'
  - 'pypy3'

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          update: true
          packages:
            - pyenv
      language: bash
      python: '3.8.0'
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      env: # eval "$(pyenv init -)"
        - PYENV_VERSION='3.8.0'
        - PATH=$HOME/.pyenv/shims:$PATH
      before_install:
        - pyenv install --skip-existing $PYENV_VERSION
        - pip install --upgrade pip
      before_cache:
        - brew cleanup

    - os: windows
      language: bash
      python: '3.8.0'
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - PYTHON_VERSION='3.8.0'
      before_install:
        - choco install python --version $PYTHON_VERSION
        - python -m pip install --upgrade pip

    - &stage_deploy
      stage: deploy to test
      python: '3.8'
      if: branch = develop
      install: skip
      script: skip
      after_success: true # step before deploy must not be skipped for deploy to executed
      deploy:
        provider: pypi
        server: https://test.pypi.org/legacy/
        user: "__token__" # Password provided as environment variable on Travis
        distributions: sdist bdist_wheel

    - <<: *stage_deploy
      stage: deploy
      if: branch = master
      deploy:
        provider: pypi
        user: kressi
        password:
          secure: Rw31x5q4kz2Byld5JuboAxEISR4OIrJdobKU1mmJI8CQL8IuZOuv0w8Y7DxljQLzvCigtPFfqXkdARCXiKeYwKUAQaTVRVRf5DpPQsYlnSS8/0b6vr7XEiICkIjQN0CtB/oyXjLA7nZebgeRj45iVf4nDSzyQnjiIXpfIUTqLnA=
        distributions: sdist bdist_wheel
        on:
          tags: true

install:
  - python --version
  - pip --version
  - pip install nose
  - nosetests --version
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=terminalplot

after_success:
  - coveralls
